name: Build release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: windows-2019
    
    steps:
      - name: Install 7Zip PowerShell Module
        shell: powershell
        run: Install-Module 7Zip4PowerShell -Force
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.202'
      - uses: actions/checkout@v2
      
      - name: Fix nuget problems
        run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config
      
      - name: Restore Packages
        run: dotnet restore
      
      - name: Build Artifact
        run: dotnet publish -c Release Pinpoint.Win/Pinpoint.Win.csproj -o ./ -p:PublishSingleFile=true --self-contained false --runtime win-x64
      
      - name: Zip Artifact
        run: 7z a -zip Pinpoint-${{ github.ref }}.zip Pinpoint.exe
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Alpha ${{ github.ref }}
          draft: true
          prerelease: true
      
      - name: Upload Release Asset
        id: upload-release-asset-x64
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Pinpoint-${{ github.ref }}.zip
          asset_name: Pinpoint-${{ github.ref }}.zip
          asset_content_type: application/zip
